# Generated by Django 5.1.15 on 2026-01-30 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcube', '0004_userpreference_fields'),
        ('workflows', '0002_flowcube_30_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_phone', models.CharField(db_index=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_instance', models.CharField(blank=True, help_text='Evolution API instance name', max_length=100)),
                ('current_node_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting_input', 'Waiting for Input'), ('waiting_ai', 'Waiting for AI'), ('handoff', 'Human Handoff'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('handoff_reason', models.TextField(blank=True)),
                ('salescube_lead_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (from user)'), ('outbound', 'Outbound (from bot/agent)')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('template', 'WhatsApp Template'), ('interactive', 'Interactive (buttons/list)')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data like buttons, template params')),
                ('from_node_id', models.CharField(blank=True, help_text='Node that generated this message', max_length=100)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, help_text='Model used: gpt-4o, claude, etc', max_length=50)),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('whatsapp_status', models.CharField(blank=True, help_text='sent, delivered, read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='flowcube.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='flowcube.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('explicit_request', 'User requested human'), ('sentiment_negative', 'Negative sentiment detected'), ('confidence_low', 'AI confidence too low'), ('escalation_keyword', 'Escalation keyword detected'), ('loop_detected', 'Conversation loop detected'), ('complex_query', 'Complex query'), ('manual', 'Manual escalation')], max_length=30)),
                ('reason_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('conversation_summary', models.TextField(blank=True)),
                ('collected_variables', models.JSONField(default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_requests', to='flowcube.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['contact_phone', 'workflow'], name='flowcube_ch_contact_681c74_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', 'last_message_at'], name='flowcube_ch_status_f0c0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappwebhooklog',
            index=models.Index(fields=['instance', 'event_type'], name='flowcube_wh_instanc_a0543f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappwebhooklog',
            index=models.Index(fields=['processed', 'created_at'], name='flowcube_wh_process_c84d13_idx'),
        ),
    ]
