# Generated by Codex to align DB schema with flowcube.models.FlowExecutionLog

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcube', '0005_chat_models'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executor', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')],
                        default='STARTED',
                        max_length=50,
                    ),
                ),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                (
                    'workflow',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='execution_logs',
                        to='workflows.workflow',
                    ),
                ),
            ],
            options={
                'ordering': ['-start_time'],
                'verbose_name_plural': 'Flow Execution Logs',
            },
        ),
    ]
