# Generated by Django 5.1.15 on 2026-02-06 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0005_merge_20260205_2047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Bot token from @BotFather', max_length=100)),
                ('bot_id', models.BigIntegerField(blank=True, help_text='Telegram bot ID (extracted from token)', null=True)),
                ('username', models.CharField(blank=True, help_text='Bot username without @', max_length=64)),
                ('first_name', models.CharField(blank=True, help_text='Bot display name', max_length=64)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for receiving updates', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret token for webhook verification', max_length=256)),
                ('webhook_set_at', models.DateTimeField(blank=True, help_text='When webhook was last configured', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether bot token was verified with Telegram')),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, help_text='Workflow to execute when messages arrive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_bots', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Telegram chat ID')),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], default='private', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Group/channel title', max_length=256)),
                ('username', models.CharField(blank=True, help_text='Chat username if available', max_length=64)),
                ('first_name', models.CharField(blank=True, help_text='User first name (for private chats)', max_length=64)),
                ('last_name', models.CharField(blank=True, help_text='User last name (for private chats)', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Whether bot can send messages to this chat')),
                ('is_blocked', models.BooleanField(default=False, help_text='User blocked the bot')),
                ('current_node_id', models.CharField(blank=True, help_text='Current workflow node', max_length=100)),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Collected variables during conversation')),
                ('context', models.JSONField(blank=True, default=dict, help_text='AI conversation context')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='telegram_integration.telegrambot')),
            ],
            options={
                'verbose_name': 'Telegram Chat',
                'verbose_name_plural': 'Telegram Chats',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_query_id', models.CharField(db_index=True, help_text='Telegram callback query ID', max_length=64)),
                ('data', models.CharField(help_text='Callback data sent with the button', max_length=64)),
                ('message_id', models.BigIntegerField(blank=True, help_text='Message ID the callback is from', null=True)),
                ('inline_message_id', models.CharField(blank=True, help_text='Inline message ID (for inline mode)', max_length=64)),
                ('from_user_id', models.BigIntegerField(help_text='Telegram user ID who clicked')),
                ('answered', models.BooleanField(default=False, help_text='Whether callback was answered')),
                ('answer_text', models.CharField(blank=True, help_text='Text shown in answer', max_length=200)),
                ('answer_show_alert', models.BooleanField(default=False, help_text='Whether answer was shown as alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='telegram_integration.telegramchat')),
            ],
            options={
                'verbose_name': 'Telegram Callback',
                'verbose_name_plural': 'Telegram Callbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.BigIntegerField(db_index=True, help_text='Telegram message ID within the chat')),
                ('direction', models.CharField(choices=[('in', 'Inbound (from user)'), ('out', 'Outbound (from bot)')], max_length=5)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Voice'), ('document', 'Document'), ('sticker', 'Sticker'), ('animation', 'Animation/GIF'), ('location', 'Location'), ('contact', 'Contact'), ('poll', 'Poll'), ('venue', 'Venue'), ('dice', 'Dice'), ('game', 'Game'), ('invoice', 'Invoice'), ('unknown', 'Unknown')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content or caption')),
                ('media_url', models.URLField(blank=True, help_text='URL to media file', max_length=1000)),
                ('media_file_id', models.CharField(blank=True, help_text='Telegram file_id for media', max_length=200)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, help_text='ID of message this is replying to', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message data (buttons, entities, etc)')),
                ('from_node_id', models.CharField(blank=True, help_text='Workflow node that generated this message', max_length=100)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, help_text='AI model used (gpt-4o, claude, etc)', max_length=50)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_date', models.DateTimeField(blank=True, help_text='Message timestamp from Telegram', null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_integration.telegramchat')),
            ],
            options={
                'verbose_name': 'Telegram Message',
                'verbose_name_plural': 'Telegram Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_id', models.BigIntegerField(db_index=True, help_text='Telegram update ID')),
                ('event_type', models.CharField(help_text='Type of update (message, callback_query, etc)', max_length=50)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='telegram_integration.telegrambot')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='telegram_integration.telegramchat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='telegram_integration.telegrammessage')),
            ],
            options={
                'verbose_name': 'Telegram Webhook Log',
                'verbose_name_plural': 'Telegram Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegrambot',
            index=models.Index(fields=['owner', 'is_active'], name='telegram_in_owner_i_e9d1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambot',
            index=models.Index(fields=['bot_id'], name='telegram_in_bot_id_e96bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramchat',
            index=models.Index(fields=['bot', 'chat_id'], name='telegram_in_bot_id_1fdf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramchat',
            index=models.Index(fields=['chat_type', 'is_active'], name='telegram_in_chat_ty_3950f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telegramchat',
            unique_together={('bot', 'chat_id')},
        ),
        migrations.AddIndex(
            model_name='telegramcallback',
            index=models.Index(fields=['callback_query_id'], name='telegram_in_callbac_6c0a88_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramcallback',
            index=models.Index(fields=['chat', 'message_id'], name='telegram_in_chat_id_f073bc_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['chat', 'message_id'], name='telegram_in_chat_id_e87de4_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['direction', 'created_at'], name='telegram_in_directi_c57248_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramwebhooklog',
            index=models.Index(fields=['bot', 'update_id'], name='telegram_in_bot_id_99692a_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramwebhooklog',
            index=models.Index(fields=['processed', 'created_at'], name='telegram_in_process_8e9de8_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramwebhooklog',
            index=models.Index(fields=['event_type'], name='telegram_in_event_t_508f97_idx'),
        ),
    ]
