# Generated by Django 5.1.15 on 2026-02-06 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, help_text='Frase de destaque para marketing', max_length=200)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_discount_percentage', models.DecimalField(decimal_places=2, default=20, help_text='Desconto aplicado no plano anual (padrão 20%)', max_digits=5)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('max_workflows', models.IntegerField(default=5, help_text='Número máximo de workflows que podem ser criados')),
                ('max_executions_per_month', models.IntegerField(default=100, help_text='Número máximo de execuções de workflow por mês')),
                ('max_nodes_per_workflow', models.IntegerField(blank=True, help_text='Número máximo de nodes por workflow (null = ilimitado)', null=True)),
                ('max_active_workflows', models.IntegerField(default=3, help_text='Número máximo de workflows ativos simultaneamente')),
                ('max_ai_requests_per_month', models.IntegerField(default=0, help_text='Número máximo de requisições AI por mês (0 = sem acesso)')),
                ('max_storage_mb', models.IntegerField(default=100, help_text='Armazenamento máximo em MB')),
                ('has_ai_features', models.BooleanField(default=False, help_text='Acesso a AI Node Builder, AI Debugger, AI Assistant')),
                ('has_marketplace_access', models.BooleanField(default=True, help_text='Acesso ao Marketplace de workflows')),
                ('has_marketplace_publish', models.BooleanField(default=False, help_text='Pode publicar workflows no Marketplace')),
                ('has_whatsapp_integration', models.BooleanField(default=False, help_text='Integração com WhatsApp Business API')),
                ('has_advanced_analytics', models.BooleanField(default=False, help_text='Analytics avançado com métricas premium')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Suporte prioritário')),
                ('has_whitelabel', models.BooleanField(default=False, help_text='Pode usar marca própria (white label)')),
                ('has_api_access', models.BooleanField(default=False, help_text='Acesso à API REST do FlowCube')),
                ('has_custom_domain', models.BooleanField(default=False, help_text='Pode usar domínio customizado')),
                ('has_team_collaboration', models.BooleanField(default=False, help_text='Recursos de colaboração em equipe')),
                ('max_team_members', models.IntegerField(default=1, help_text='Número máximo de membros da equipe')),
                ('features', models.JSONField(default=list, help_text='Lista de features para exibição (ex: ["Feature 1", "Feature 2"])')),
                ('is_popular', models.BooleanField(default=False, help_text='Marcar como plano mais popular')),
                ('is_active', models.BooleanField(default=True, help_text='Plano disponível para compra')),
                ('display_order', models.IntegerField(default=0, help_text='Ordem de exibição (menor primeiro)')),
                ('trial_days', models.IntegerField(default=14, help_text='Dias de trial gratuito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=20)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('pix_key', models.CharField(blank=True, max_length=255)),
                ('pix_key_type', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('paused', 'Paused')], default='active', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('pix', 'Pix'), ('boleto', 'Boleto')], default='credit_card', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255)),
                ('stripe_hosted_invoice_url', models.URLField(blank=True)),
                ('stripe_invoice_pdf', models.URLField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='draft', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('pix', 'Pix'), ('boleto', 'Boleto')], default='credit_card', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='billing_inv_subscri_4c8e1f_idx'), models.Index(fields=['stripe_invoice_id'], name='billing_inv_stripe__1798ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('stripe_event_id', models.CharField(blank=True, max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='billing_bil_event_t_586f4d_idx'), models.Index(fields=['stripe_event_id'], name='billing_bil_stripe__b2aeb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Primeiro dia do mês de referência')),
                ('workflows_count', models.IntegerField(default=0, help_text='Total de workflows criados')),
                ('active_workflows_count', models.IntegerField(default=0, help_text='Workflows ativos')),
                ('executions_count', models.IntegerField(default=0, help_text='Execuções de workflow')),
                ('ai_requests_count', models.IntegerField(default=0, help_text='Requisições AI')),
                ('ai_tokens_used', models.BigIntegerField(default=0, help_text='Tokens AI consumidos')),
                ('storage_used_mb', models.FloatField(default=0, help_text='Armazenamento usado em MB')),
                ('whatsapp_messages_sent', models.IntegerField(default=0)),
                ('api_requests_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['user', 'month'], name='billing_usa_user_id_71cb70_idx')],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
