# Generated by Django - placeholder migration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_flowcube_30_upgrade'),
    ]

    operations = [
        # Empty migration to maintain migration chain
    ]
