# Generated by Django 5.1.15 on 2026-02-04 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_add_ai_assistant_models_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do assistente', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descrição do assistente')),
                ('context_patterns', models.JSONField(default=dict, help_text="Padrões de contexto brasileiro: {'pix': [...], 'whatsapp': [...], 'nfe': [...]}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistente IA',
                'verbose_name_plural': 'Assistentes IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrazilianContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('pix', 'Pix'), ('whatsapp', 'WhatsApp Business'), ('nfe', 'Nota Fiscal Eletrônica'), ('ecommerce', 'E-commerce'), ('crm', 'CRM'), ('leads', 'Gestão de Leads')], max_length=50, unique=True)),
                ('patterns', models.JSONField(default=list, help_text='Lista de padrões/keywords para identificar este contexto')),
                ('templates', models.JSONField(default=list, help_text='Templates de workflow para este contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contexto Brasileiro',
                'verbose_name_plural': 'Contextos Brasileiros',
            },
        ),
        migrations.CreateModel(
            name='AutomationSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_template', models.JSONField(default=dict, help_text='Template completo do workflow (nodes, edges, config)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Score de 0 a 100 indicando confiança na sugestão')),
                ('context_type', models.CharField(blank=True, help_text='Tipo de contexto brasileiro identificado', max_length=50)),
                ('user_context', models.JSONField(default=dict, help_text='Contexto fornecido pelo usuário para análise')),
                ('explanation', models.TextField(blank=True, help_text='Explicação de por que esta automação foi sugerida')),
                ('is_applied', models.BooleanField(default=False, help_text='Se a sugestão foi aplicada ao workflow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_to_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='workflows.workflow')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='workflows.aiassistant')),
            ],
            options={
                'verbose_name': 'Sugestão de Automação',
                'verbose_name_plural': 'Sugestões de Automação',
                'ordering': ['-created_at'],
            },
        ),
    ]
