# Generated by Django 5.1.15 on 2026-02-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_block_block_type'),
        ('workflows', '0004_add_ai_assistant_models_v2'),
    ]

    operations = [
    ]
