# Generated by Django 5.1.15 on 2026-02-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_execution_parent_execution_workflowschedule'),
        ('workflows', '0007_workflowschedule_parent_execution'),
    ]

    operations = [
    ]
