# Generated by Django 5.1.15 on 2026-02-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_merge_20260217_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('google_organic', 'Google Organic'), ('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('direct', 'Direct Traffic'), ('email_campaign', 'Email Campaign'), ('referral', 'Referral'), ('landing_page', 'Landing Page'), ('sales_page', 'Sales Page'), ('product_page', 'Product Page'), ('checkout', 'Checkout'), ('thank_you', 'Thank You Page'), ('blog_post', 'Blog Post'), ('button_click', 'Button Click'), ('form_submit', 'Form Submit'), ('purchase', 'Purchase'), ('sign_up', 'Sign Up'), ('add_to_cart', 'Add to Cart'), ('download', 'Download'), ('video_view', 'Video View'), ('custom_event', 'Custom Event'), ('email_sequence', 'Email Sequence'), ('tag_segment', 'Tag/Segmentation'), ('webhook', 'Webhook'), ('decision_tree', 'Decision Tree'), ('wait', 'Wait/Delay'), ('whatsapp_trigger', 'WhatsApp Trigger'), ('schedule', 'Schedule'), ('facebook_lead_ads', 'Facebook Lead Ads'), ('deduplicate', 'Deduplicate'), ('send_to_salescube', 'Send to SalesCube'), ('openai', 'OpenAI'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('text_input', 'Text Input'), ('email_input', 'Email Input'), ('phone_input', 'Phone Input'), ('choice', 'Choice'), ('condition', 'Condition'), ('set_variable', 'Set Variable'), ('text_response', 'Text Response'), ('image_response', 'Image Response'), ('whatsapp_template', 'WhatsApp Template')], max_length=50),
        ),
    ]
