# Generated by Django 5.1.15 on 2026-02-10 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAdsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64)),
                ('_app_secret', models.TextField(db_column='app_secret')),
                ('verify_token', models.CharField(max_length=128)),
                ('webhook_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Ads App Config',
                'db_table': 'socialcube_leadads_appconfig',
            },
        ),
        migrations.CreateModel(
            name='LeadAdsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=64, unique=True)),
                ('page_name', models.CharField(blank=True, max_length=255)),
                ('_page_access_token', models.TextField(db_column='page_access_token')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('webhook_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'socialcube_leadads_connection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('pending_approval', 'Aguardando Aprovacao'), ('approved', 'Aprovado'), ('publishing', 'Publicando'), ('published', 'Publicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('permalink', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('threads', 'Threads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('bluesky', 'Bluesky'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('twitter', 'X/Twitter')], max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('platform_user_id', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'platform', 'username')},
            },
        ),
        migrations.CreateModel(
            name='LeadAdsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=64, unique=True)),
                ('form_name', models.CharField(blank=True, max_length=255)),
                ('form_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('distribution_mode', models.CharField(choices=[('none', 'No Distribution'), ('salescube', 'SalesCube CRM'), ('webhook', 'External Webhook')], default='none', max_length=20)),
                ('distribution_config', models.JSONField(blank=True, default=dict)),
                ('leads_count', models.IntegerField(default=0)),
                ('last_lead_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='socialcube.leadadsconnection')),
            ],
            options={
                'db_table': 'socialcube_leadads_form',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(max_length=64, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('distribution_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='socialcube.leadadsform')),
            ],
            options={
                'db_table': 'socialcube_leadads_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('video_views', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('post_platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='socialcube.postplatform')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('pending_approval', 'Aguardando Aprovacao'), ('approved', 'Aprovado'), ('publishing', 'Publicando'), ('published', 'Publicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('first_comment', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='postplatform',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='socialcube.scheduledpost'),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='socialcube/media/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='image', max_length=10)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='socialcube.scheduledpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SmartLinkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('theme', models.JSONField(blank=True, default=dict, help_text='Theme config: colors, fonts, style')),
                ('is_active', models.BooleanField(default=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartLinkButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='socialcube.smartlinkpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('threads', 'Threads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('bluesky', 'Bluesky'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('twitter', 'X/Twitter')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('profile_image_url', models.URLField(blank=True, max_length=500)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
                'unique_together': {('user', 'platform', 'platform_user_id')},
            },
        ),
        migrations.AddField(
            model_name='postplatform',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_platforms', to='socialcube.socialaccount'),
        ),
        migrations.AddField(
            model_name='leadadsconnection',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadads_connections', to='socialcube.socialaccount'),
        ),
        migrations.CreateModel(
            name='CompetitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('avg_likes', models.FloatField(default=0.0)),
                ('avg_comments', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('top_hashtags', models.JSONField(blank=True, default=list)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='socialcube.competitor')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('competitor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ContentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reviews', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='socialcube.scheduledpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'reviewer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='postplatform',
            unique_together={('post', 'account')},
        ),
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers', models.PositiveIntegerField(default=0)),
                ('followers_gained', models.IntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('website_clicks', models.PositiveIntegerField(default=0)),
                ('total_impressions', models.PositiveIntegerField(default=0)),
                ('total_reach', models.PositiveIntegerField(default=0)),
                ('total_engagement', models.PositiveIntegerField(default=0)),
                ('best_posting_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='socialcube.socialaccount')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
