# Generated by Django 5.1.15 on 2026-02-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatcube', '0005_contact_assigned_to'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='msg_instance_time_idx',
            old_name='chatcube_me_instanc_40d6b9_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='msg_jid_time_idx',
            old_name='chatcube_me_remote__c64014_idx',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='engine_instance_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['instance', 'remote_jid', '-timestamp'], name='msg_conv_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['wa_message_id'], name='msg_wa_id_idx'),
        ),
    ]
