# Generated by Django 5.1.15 on 2026-02-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescube', '0006_franchise_origin_tasktype_lead_responsibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
