# Generated by Django 5.1.15 on 2026-02-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescube', '0007_add_contact_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
