# Generated by Django 5.1.15 on 2026-02-15 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salescube', '0004_contact_emailtemplate_invoice_invoiceitem_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('strategy', models.CharField(choices=[('ringall', 'Ring All'), ('leastrecent', 'Least Recent'), ('fewestcalls', 'Fewest Calls'), ('random', 'Random'), ('rrmemory', 'Round Robin (Memory)')], default='ringall', max_length=50)),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Ring timeout per agent (seconds)')),
                ('max_wait_time', models.PositiveIntegerField(default=300, help_text='Max caller wait time (seconds)')),
                ('music_on_hold', models.CharField(default='default', help_text='Music on hold class', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IVRMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('greeting_audio_s3_key', models.CharField(blank=True, default='', max_length=512)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('timeout_destination', models.CharField(help_text='e.g., queue:support or extension:1000', max_length=100)),
                ('invalid_destination', models.CharField(max_length=100)),
                ('max_retries', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_number', models.CharField(help_text='SIP extension number, e.g., 1001', max_length=20, unique=True)),
                ('sip_password', models.CharField(max_length=80)),
                ('webrtc_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('ON_CALL', 'On Call'), ('RINGING', 'Ringing'), ('DND', 'Do Not Disturb')], default='UNAVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['extension_number'],
            },
        ),
        migrations.CreateModel(
            name='VoicemailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_number', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('audio_s3_key', models.CharField(max_length=512)),
                ('transcription', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voicemails', to='telephony.extension')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pabx_call_id', models.CharField(db_index=True, help_text='Unique call ID from Asterisk', max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('INTERNAL', 'Internal')], max_length=10)),
                ('status', models.CharField(choices=[('RINGING', 'Ringing'), ('ANSWERED', 'Answered'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='RINGING', max_length=20)),
                ('caller_number', models.CharField(db_index=True, max_length=50)),
                ('callee_number', models.CharField(db_index=True, max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('recording_s3_key', models.CharField(blank=True, help_text='S3/MinIO object key for the recording file', max_length=512, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('disposition', models.CharField(blank=True, default='', help_text='Call outcome: Sale, Follow-up, Not Interested, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='salescube.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='salescube.lead')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['caller_number', 'start_time'], name='telephony_c_caller__fc16d6_idx'), models.Index(fields=['agent', 'start_time'], name='telephony_c_agent_i_692986_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('answered_calls', models.PositiveIntegerField(default=0)),
                ('missed_calls', models.PositiveIntegerField(default=0)),
                ('outbound_calls', models.PositiveIntegerField(default=0)),
                ('avg_duration', models.FloatField(default=0.0)),
                ('total_talk_time', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_call_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'agent'],
                'unique_together': {('date', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='IVROption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.CharField(help_text='e.g., 1, 2, #', max_length=2)),
                ('label', models.CharField(help_text='e.g., Vendas, Suporte', max_length=100)),
                ('destination_type', models.CharField(choices=[('EXTENSION', 'Extension'), ('QUEUE', 'Call Queue'), ('IVR_MENU', 'IVR Menu'), ('VOICEMAIL', 'Voicemail'), ('EXTERNAL', 'External Number'), ('HANGUP', 'Hangup')], max_length=20)),
                ('destination_id', models.CharField(max_length=100)),
                ('ivr_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='telephony.ivrmenu')),
            ],
            options={
                'unique_together': {('ivr_menu', 'digit')},
            },
        ),
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='telephony.extension')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='telephony.callqueue')),
            ],
            options={
                'unique_together': {('queue', 'extension')},
            },
        ),
    ]
