/**
 * Node Visual Config - Central registry for Make.com-style node visuals
 *
 * Maps every node type to its icon, color, shape, and display properties.
 * Single source of truth - no more scattered configs across 13+ component files.
 */
import {
  Webhook,
  Clock,
  MessageSquare,
  Zap,
  Globe,
  Send,
  Bot,
  Brain,
  Sparkles,
  Cpu,
  GitBranch,
  GitMerge,
  Variable,
  Timer,
  Shuffle,
  Repeat,
  Layers,
  FileText,
  Filter,
  ArrowUpDown,
  MessageCircle,
  Image,
  Mail,
  Phone,
  Users,
  Share2,
  BarChart3,
  Search,
  DollarSign,
  Target,
  MousePointer,
  FormInput,
  ShoppingCart,
  ScrollText,
  Video,
  Layout,
  CreditCard,
  Gift,
  TrendingDown,
  AlertTriangle,
  Workflow,
  Keyboard,
  type LucideIcon,
} from "lucide-react";

export interface NodeVisualDef {
  icon: LucideIcon;
  color: string; // tailwind color name: "blue", "amber", etc.
  subtitle: string;
  shape: "circle" | "hexagon" | "diamond";
  badge?: string;
  hasInput: boolean;
  hasOutput: boolean;
}

// Color palette maps color keys to Tailwind class fragments
export const COLOR_PALETTE: Record<
  string,
  {
    bg: string;
    bgLight: string;
    text: string;
    border: string;
    borderSelected: string;
    glow: string;
    handle: string;
    handleBorder: string;
  }
> = {
  amber: {
    bg: "bg-amber-500",
    bgLight: "bg-amber-500/15",
    text: "text-amber-400",
    border: "border-amber-500/30",
    borderSelected: "border-amber-400",
    glow: "shadow-amber-400/30",
    handle: "!bg-amber-400",
    handleBorder: "!border-amber-600",
  },
  blue: {
    bg: "bg-blue-500",
    bgLight: "bg-blue-500/15",
    text: "text-blue-400",
    border: "border-blue-500/30",
    borderSelected: "border-blue-400",
    glow: "shadow-blue-400/30",
    handle: "!bg-blue-400",
    handleBorder: "!border-blue-600",
  },
  pink: {
    bg: "bg-pink-500",
    bgLight: "bg-pink-500/15",
    text: "text-pink-400",
    border: "border-pink-500/30",
    borderSelected: "border-pink-400",
    glow: "shadow-pink-400/30",
    handle: "!bg-pink-400",
    handleBorder: "!border-pink-600",
  },
  red: {
    bg: "bg-red-500",
    bgLight: "bg-red-500/15",
    text: "text-red-400",
    border: "border-red-500/30",
    borderSelected: "border-red-400",
    glow: "shadow-red-400/30",
    handle: "!bg-red-400",
    handleBorder: "!border-red-600",
  },
  purple: {
    bg: "bg-purple-500",
    bgLight: "bg-purple-500/15",
    text: "text-purple-400",
    border: "border-purple-500/30",
    borderSelected: "border-purple-400",
    glow: "shadow-purple-400/30",
    handle: "!bg-purple-400",
    handleBorder: "!border-purple-600",
  },
  sky: {
    bg: "bg-sky-500",
    bgLight: "bg-sky-500/15",
    text: "text-sky-400",
    border: "border-sky-500/30",
    borderSelected: "border-sky-400",
    glow: "shadow-sky-400/30",
    handle: "!bg-sky-400",
    handleBorder: "!border-sky-600",
  },
  teal: {
    bg: "bg-teal-500",
    bgLight: "bg-teal-500/15",
    text: "text-teal-400",
    border: "border-teal-500/30",
    borderSelected: "border-teal-400",
    glow: "shadow-teal-400/30",
    handle: "!bg-teal-400",
    handleBorder: "!border-teal-600",
  },
  orange: {
    bg: "bg-orange-500",
    bgLight: "bg-orange-500/15",
    text: "text-orange-400",
    border: "border-orange-500/30",
    borderSelected: "border-orange-400",
    glow: "shadow-orange-400/30",
    handle: "!bg-orange-400",
    handleBorder: "!border-orange-600",
  },
  coral: {
    bg: "bg-primary",
    bgLight: "bg-primary/15",
    text: "text-primary",
    border: "border-primary/30",
    borderSelected: "border-primary",
    glow: "shadow-primary/30",
    handle: "!bg-primary",
    handleBorder: "!border-primary/60",
  },
  indigo: {
    bg: "bg-indigo-500",
    bgLight: "bg-indigo-500/15",
    text: "text-indigo-400",
    border: "border-indigo-500/30",
    borderSelected: "border-indigo-400",
    glow: "shadow-indigo-400/30",
    handle: "!bg-indigo-400",
    handleBorder: "!border-indigo-600",
  },
  cyan: {
    bg: "bg-cyan-500",
    bgLight: "bg-cyan-500/15",
    text: "text-cyan-400",
    border: "border-cyan-500/30",
    borderSelected: "border-cyan-400",
    glow: "shadow-cyan-400/30",
    handle: "!bg-cyan-400",
    handleBorder: "!border-cyan-600",
  },
  violet: {
    bg: "bg-violet-500",
    bgLight: "bg-violet-500/15",
    text: "text-violet-400",
    border: "border-violet-500/30",
    borderSelected: "border-violet-400",
    glow: "shadow-violet-400/30",
    handle: "!bg-violet-400",
    handleBorder: "!border-violet-600",
  },
  emerald: {
    bg: "bg-emerald-500",
    bgLight: "bg-emerald-500/15",
    text: "text-emerald-400",
    border: "border-emerald-500/30",
    borderSelected: "border-emerald-400",
    glow: "shadow-emerald-400/30",
    handle: "!bg-emerald-400",
    handleBorder: "!border-emerald-600",
  },
};

export const NODE_VISUAL_CONFIG: Record<string, NodeVisualDef> = {
  // ── Triggers (hexagon, amber) ───────────────────────────
  webhook_trigger: {
    icon: Webhook,
    color: "amber",
    subtitle: "Webhook",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  schedule: {
    icon: Clock,
    color: "amber",
    subtitle: "Schedule",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  whatsapp_trigger: {
    icon: MessageSquare,
    color: "amber",
    subtitle: "WhatsApp",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  evolution_trigger: {
    icon: MessageSquare,
    color: "amber",
    subtitle: "Evolution API",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  manual_trigger: {
    icon: Zap,
    color: "amber",
    subtitle: "Manual",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },

  // ── HTTP / API (circle, blue) ───────────────────────────
  http_request: {
    icon: Globe,
    color: "blue",
    subtitle: "HTTP Request",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  webhook: {
    icon: Webhook,
    color: "blue",
    subtitle: "Send Webhook",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  n8n_webhook: {
    icon: Webhook,
    color: "blue",
    subtitle: "N8N Webhook",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  send_email: {
    icon: Mail,
    color: "blue",
    subtitle: "Email",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── AI / LLM (circle, pink) ────────────────────────────
  openai: {
    icon: Bot,
    color: "pink",
    subtitle: "OpenAI",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  claude: {
    icon: Brain,
    color: "pink",
    subtitle: "Claude",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  deepseek: {
    icon: Sparkles,
    color: "pink",
    subtitle: "DeepSeek",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  ai: {
    icon: Cpu,
    color: "pink",
    subtitle: "AI",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  llm: {
    icon: Cpu,
    color: "pink",
    subtitle: "LLM",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── Logic (diamond, red) ───────────────────────────────
  condition: {
    icon: GitBranch,
    color: "red",
    subtitle: "If/Else",
    shape: "diamond",
    hasInput: true,
    hasOutput: true,
  },
  decision_tree: {
    icon: GitBranch,
    color: "red",
    subtitle: "Decision Tree",
    shape: "diamond",
    hasInput: true,
    hasOutput: true,
  },
  set_variable: {
    icon: Variable,
    color: "red",
    subtitle: "Set Variable",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  wait: {
    icon: Timer,
    color: "red",
    subtitle: "Delay",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  merge: {
    icon: GitMerge,
    color: "red",
    subtitle: "Merge",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── Router (diamond, purple) ───────────────────────────
  router: {
    icon: GitBranch,
    color: "purple",
    subtitle: "Router",
    shape: "diamond",
    hasInput: true,
    hasOutput: true,
  },

  // ── Data Transform (circle, sky) ───────────────────────
  json_transform: {
    icon: Shuffle,
    color: "sky",
    subtitle: "JSON Transform",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  iterator: {
    icon: Repeat,
    color: "sky",
    subtitle: "Iterator",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  aggregator: {
    icon: Layers,
    color: "sky",
    subtitle: "Aggregator",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  text_parser: {
    icon: FileText,
    color: "sky",
    subtitle: "Text Parser",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  filter: {
    icon: Filter,
    color: "sky",
    subtitle: "Filter",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  sort: {
    icon: ArrowUpDown,
    color: "sky",
    subtitle: "Sort",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── Output (circle, teal) ─────────────────────────────
  text_response: {
    icon: MessageCircle,
    color: "teal",
    subtitle: "Text",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  whatsapp_template: {
    icon: MessageSquare,
    color: "teal",
    subtitle: "WA Template",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  image_response: {
    icon: Image,
    color: "teal",
    subtitle: "Image",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── CRM / SalesCube (circle, orange, badge) ────────────
  salescube_create_lead: {
    icon: Users,
    color: "orange",
    subtitle: "Create Lead",
    shape: "circle",
    badge: "SalesCube",
    hasInput: true,
    hasOutput: true,
  },
  salescube_update_lead: {
    icon: Users,
    color: "orange",
    subtitle: "Update Lead",
    shape: "circle",
    badge: "SalesCube",
    hasInput: true,
    hasOutput: true,
  },

  // ── FlowCube Modules (circle, coral, badge) ────────────
  chatcube_send: {
    icon: MessageCircle,
    color: "emerald",
    subtitle: "Send Message",
    shape: "circle",
    badge: "ChatCube",
    hasInput: true,
    hasOutput: true,
  },
  whatsapp_send: {
    icon: Phone,
    color: "emerald",
    subtitle: "Send WA",
    shape: "circle",
    badge: "ChatCube",
    hasInput: true,
    hasOutput: true,
  },
  socialcube_post: {
    icon: Share2,
    color: "coral",
    subtitle: "Post",
    shape: "circle",
    badge: "SocialCube",
    hasInput: true,
    hasOutput: true,
  },
  funnelcube_track: {
    icon: BarChart3,
    color: "coral",
    subtitle: "Track Event",
    shape: "circle",
    badge: "FunnelCube",
    hasInput: true,
    hasOutput: true,
  },
  pagecube_submissions: {
    icon: FileText,
    color: "coral",
    subtitle: "Form Data",
    shape: "circle",
    badge: "PageCube",
    hasInput: true,
    hasOutput: true,
  },
  sub_workflow: {
    icon: Workflow,
    color: "coral",
    subtitle: "Sub-Workflow",
    shape: "circle",
    badge: "FlowCube",
    hasInput: true,
    hasOutput: true,
  },

  // ── Analytics / Traffic (circle, indigo) ───────────────
  google_organic: {
    icon: Search,
    color: "indigo",
    subtitle: "Google Organic",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  google_ads: {
    icon: DollarSign,
    color: "indigo",
    subtitle: "Google Ads",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  facebook_ads: {
    icon: Target,
    color: "indigo",
    subtitle: "Facebook Ads",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  meta_ads: {
    icon: Target,
    color: "indigo",
    subtitle: "Meta Ads",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  direct: {
    icon: Globe,
    color: "indigo",
    subtitle: "Direct",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  referral: {
    icon: Share2,
    color: "indigo",
    subtitle: "Referral",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  social: {
    icon: Share2,
    color: "indigo",
    subtitle: "Social",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── Pages (circle, indigo) ────────────────────────────
  landing_page: {
    icon: Layout,
    color: "indigo",
    subtitle: "Landing Page",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  sales_page: {
    icon: Layout,
    color: "indigo",
    subtitle: "Sales Page",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  checkout: {
    icon: CreditCard,
    color: "indigo",
    subtitle: "Checkout",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  thank_you: {
    icon: Gift,
    color: "indigo",
    subtitle: "Thank You",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  upsell: {
    icon: TrendingDown,
    color: "indigo",
    subtitle: "Upsell",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  downsell: {
    icon: TrendingDown,
    color: "indigo",
    subtitle: "Downsell",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── Actions (circle, indigo) ──────────────────────────
  button_click: {
    icon: MousePointer,
    color: "indigo",
    subtitle: "Button Click",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  form_submit: {
    icon: FormInput,
    color: "indigo",
    subtitle: "Form Submit",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  purchase: {
    icon: ShoppingCart,
    color: "indigo",
    subtitle: "Purchase",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  custom_event: {
    icon: Zap,
    color: "indigo",
    subtitle: "Custom Event",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  scroll: {
    icon: ScrollText,
    color: "indigo",
    subtitle: "Scroll",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  video_play: {
    icon: Video,
    color: "indigo",
    subtitle: "Video Play",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── Telegram (circle, cyan) ───────────────────────────
  telegram_trigger: {
    icon: Send,
    color: "cyan",
    subtitle: "TG Trigger",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  telegram_message_trigger: {
    icon: Send,
    color: "cyan",
    subtitle: "TG Message",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  telegram_command_trigger: {
    icon: Send,
    color: "cyan",
    subtitle: "TG Command",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  telegram_callback_trigger: {
    icon: Send,
    color: "cyan",
    subtitle: "TG Callback",
    shape: "hexagon",
    hasInput: false,
    hasOutput: true,
  },
  telegram_send: {
    icon: Send,
    color: "cyan",
    subtitle: "TG Send",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_send_message: {
    icon: Send,
    color: "cyan",
    subtitle: "TG Message",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_buttons: {
    icon: Keyboard,
    color: "cyan",
    subtitle: "TG Buttons",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_keyboard: {
    icon: Keyboard,
    color: "cyan",
    subtitle: "TG Keyboard",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_media: {
    icon: Image,
    color: "cyan",
    subtitle: "TG Media",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_photo: {
    icon: Image,
    color: "cyan",
    subtitle: "TG Photo",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_video: {
    icon: Video,
    color: "cyan",
    subtitle: "TG Video",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_document: {
    icon: FileText,
    color: "cyan",
    subtitle: "TG Document",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_callback: {
    icon: MousePointer,
    color: "cyan",
    subtitle: "TG Callback",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
  telegram_callback_handler: {
    icon: MousePointer,
    color: "cyan",
    subtitle: "TG Handler",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },

  // ── Error (circle, red) ───────────────────────────────
  error_handler: {
    icon: AlertTriangle,
    color: "red",
    subtitle: "Error Handler",
    shape: "circle",
    hasInput: true,
    hasOutput: true,
  },
};

// Default fallback for unknown types
export const DEFAULT_VISUAL: NodeVisualDef = {
  icon: Zap,
  color: "blue",
  subtitle: "Action",
  shape: "circle",
  hasInput: true,
  hasOutput: true,
};

export function getNodeVisual(type: string): NodeVisualDef {
  return NODE_VISUAL_CONFIG[type] || DEFAULT_VISUAL;
}
