# Generated by Django 5.1.15 on 2026-02-21 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0009_alter_block_block_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_id', models.CharField(db_index=True, help_text='Instagram-scoped user ID (IGSID)', max_length=50, unique=True)),
                ('username', models.CharField(blank=True, help_text='Instagram username without @', max_length=64)),
                ('name', models.CharField(blank=True, help_text='Account display name', max_length=128)),
                ('profile_picture_url', models.URLField(blank=True, help_text='Profile picture URL', max_length=500)),
                ('biography', models.TextField(blank=True, help_text='Account bio')),
                ('facebook_page_id', models.CharField(blank=True, db_index=True, help_text='Connected Facebook Page ID', max_length=50)),
                ('facebook_page_name', models.CharField(blank=True, help_text='Facebook Page name', max_length=128)),
                ('access_token', models.TextField(help_text='Long-lived access token for Graph API')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True)),
                ('webhook_subscribed', models.BooleanField(default=False, help_text='Whether webhook is configured for messages')),
                ('webhook_subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of granted Instagram permissions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether account credentials are verified')),
                ('daily_message_count', models.PositiveIntegerField(default=0, help_text='Messages sent today (reset daily)')),
                ('daily_message_reset_at', models.DateTimeField(blank=True, help_text='When daily message count was last reset', null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_errors', models.PositiveSmallIntegerField(default=0)),
                ('auto_reply_enabled', models.BooleanField(default=True, help_text='Enable automatic replies')),
                ('human_handover_enabled', models.BooleanField(default=True, help_text='Allow handover to human agent')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, help_text='Workflow to execute when messages arrive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_accounts', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_id', models.CharField(db_index=True, help_text='Instagram-scoped user ID of the participant', max_length=50)),
                ('participant_username', models.CharField(blank=True, help_text='Participant username', max_length=64)),
                ('participant_name', models.CharField(blank=True, help_text='Participant display name', max_length=128)),
                ('participant_profile_pic', models.URLField(blank=True, help_text='Participant profile picture URL', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('human_agent', 'Human Agent'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='active', max_length=20)),
                ('messaging_window_open', models.BooleanField(default=True, help_text='Whether 24-hour messaging window is open')),
                ('last_user_message_at', models.DateTimeField(blank=True, help_text='Last message from user (window starts here)', null=True)),
                ('is_human_agent_active', models.BooleanField(default=False, help_text='Whether conversation is handled by human agent')),
                ('handover_at', models.DateTimeField(blank=True, null=True)),
                ('current_node_id', models.CharField(blank=True, help_text='Current workflow node', max_length=100)),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Collected variables during conversation')),
                ('context', models.JSONField(blank=True, default=dict, help_text='AI conversation context')),
                ('labels', models.JSONField(blank=True, default=list, help_text='Conversation labels/tags')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='instagram_automation.instagramaccount')),
                ('human_agent_user', models.ForeignKey(blank=True, help_text='Human agent handling this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_handled_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Conversation',
                'verbose_name_plural': 'Instagram Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramIceBreaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='Question text (max 80 chars)', max_length=80)),
                ('payload', models.CharField(help_text='Data sent when question is selected', max_length=1000)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_breakers', to='instagram_automation.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram Ice Breaker',
                'verbose_name_plural': 'Instagram Ice Breakers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mid', models.CharField(blank=True, db_index=True, help_text='Instagram message ID', max_length=200)),
                ('direction', models.CharField(choices=[('in', 'Inbound (from user)'), ('out', 'Outbound (from business)')], max_length=5)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('share', 'Share (Post/Reel/Story)'), ('story_reply', 'Story Reply'), ('story_mention', 'Story Mention'), ('quick_reply', 'Quick Reply'), ('generic', 'Generic Template'), ('product', 'Product'), ('reaction', 'Reaction'), ('deleted', 'Deleted'), ('unknown', 'Unknown')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content')),
                ('send_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reply_to_mid', models.CharField(blank=True, help_text='Message ID this is replying to', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message data (attachments, quick_replies, etc)')),
                ('from_node_id', models.CharField(blank=True, help_text='Workflow node that generated this message', max_length=100)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, help_text='AI model used (gpt-4o, claude, etc)', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_unsent', models.BooleanField(default=False, help_text='User unsent the message')),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instagram_timestamp', models.DateTimeField(blank=True, help_text='Message timestamp from Instagram', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instagram_automation.instagramconversation')),
            ],
            options={
                'verbose_name': 'Instagram Message',
                'verbose_name_plural': 'Instagram Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('sticker', 'Sticker'), ('share', 'Share')], max_length=20)),
                ('url', models.URLField(help_text='Media URL', max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds for video/audio', null=True)),
                ('share_type', models.CharField(blank=True, help_text='Type of shared content (post, reel, story)', max_length=50)),
                ('share_id', models.CharField(blank=True, help_text='ID of shared post/reel/story', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='instagram_automation.instagrammessage')),
            ],
            options={
                'verbose_name': 'Instagram Media Attachment',
                'verbose_name_plural': 'Instagram Media Attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name for internal use', max_length=100)),
                ('category', models.CharField(choices=[('ACCOUNT_UPDATE', 'Account Update'), ('CONFIRMED_EVENT_UPDATE', 'Confirmed Event Update'), ('POST_PURCHASE_UPDATE', 'Post Purchase Update'), ('HUMAN_AGENT', 'Human Agent')], help_text='Message tag category', max_length=50)),
                ('template_text', models.TextField(help_text='Template text with {{variables}}')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='instagram_automation.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram Message Template',
                'verbose_name_plural': 'Instagram Message Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstagramQuickReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Button text (max 80 chars)', max_length=80)),
                ('payload', models.CharField(help_text='Data sent when button is clicked', max_length=1000)),
                ('content_type', models.CharField(default='text', help_text='text, user_phone_number, user_email', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Optional icon image URL', max_length=500)),
                ('category', models.CharField(blank=True, help_text='Category for grouping', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_replies', to='instagram_automation.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram Quick Reply',
                'verbose_name_plural': 'Instagram Quick Replies',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InstagramWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('message', 'Message'), ('message_reads', 'Message Reads'), ('message_deliveries', 'Message Deliveries'), ('message_reactions', 'Message Reactions'), ('message_echoes', 'Message Echoes'), ('messaging_seen', 'Messaging Seen'), ('messaging_postbacks', 'Postbacks'), ('messaging_referrals', 'Referrals'), ('messaging_handovers', 'Handovers'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('sender_id', models.CharField(blank=True, db_index=True, help_text='Sender IGSID', max_length=50)),
                ('recipient_id', models.CharField(blank=True, db_index=True, help_text='Recipient IGSID', max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Event timestamp from Meta', null=True)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers from webhook request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='instagram_automation.instagramaccount')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='instagram_automation.instagramconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='instagram_automation.instagrammessage')),
            ],
            options={
                'verbose_name': 'Instagram Webhook Log',
                'verbose_name_plural': 'Instagram Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['owner', 'is_active'], name='instagram_a_owner_i_2aa8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['instagram_id'], name='instagram_a_instagr_0ca371_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['facebook_page_id'], name='instagram_a_faceboo_af2a04_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramconversation',
            index=models.Index(fields=['account', 'participant_id'], name='instagram_a_account_0a3cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramconversation',
            index=models.Index(fields=['status', 'last_message_at'], name='instagram_a_status_3ee780_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramconversation',
            index=models.Index(fields=['is_human_agent_active'], name='instagram_a_is_huma_9ec042_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagramconversation',
            unique_together={('account', 'participant_id')},
        ),
        migrations.AddConstraint(
            model_name='instagramicebreaker',
            constraint=models.CheckConstraint(condition=models.Q(('order__lte', 3)), name='ice_breaker_max_order'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['conversation', 'mid'], name='instagram_a_convers_445099_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['direction', 'created_at'], name='instagram_a_directi_489619_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['send_status'], name='instagram_a_send_st_65247c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagrammessagetemplate',
            unique_together={('account', 'name')},
        ),
        migrations.AddIndex(
            model_name='instagramwebhooklog',
            index=models.Index(fields=['account', 'event_type'], name='instagram_a_account_162513_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhooklog',
            index=models.Index(fields=['processed', 'created_at'], name='instagram_a_process_6f6906_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhooklog',
            index=models.Index(fields=['sender_id'], name='instagram_a_sender__a603ab_idx'),
        ),
    ]
