# Generated by Django 5.1.15 on 2026-02-04 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Integração')),
                ('bank_code', models.CharField(choices=[('ITAU', 'Itaú'), ('BRADESCO', 'Bradesco'), ('SANTANDER', 'Santander'), ('NUBANK', 'Nubank'), ('BANCO_INTER', 'Banco Inter'), ('BANCO_DO_BRASIL', 'Banco do Brasil'), ('CAIXA', 'Caixa Econômica Federal')], max_length=20, verbose_name='Código do Banco')),
                ('api_credentials', models.TextField(help_text='JSON com client_id, client_secret, api_key, etc', verbose_name='Credenciais API (Criptografadas)')),
                ('api_endpoint', models.URLField(max_length=500, verbose_name='Endpoint da API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret')),
                ('auto_reconcile', models.BooleanField(default=True, verbose_name='Reconciliação Automática')),
            ],
            options={
                'verbose_name': 'Integração Pix',
                'verbose_name_plural': 'Integrações Pix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('status', models.CharField(choices=[('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('ERROR', 'Erro'), ('PENDING', 'Pendente')], default='PENDING', max_length=20, verbose_name='Status')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('connection_metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados da Conexão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='payments.pixintegration', verbose_name='Integração')),
            ],
            options={
                'verbose_name': 'Conexão Bancária',
                'verbose_name_plural': 'Conexões Bancárias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PixTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID da transação no banco', max_length=255, unique=True, verbose_name='ID Externo')),
                ('txid', models.CharField(blank=True, help_text='Transaction ID Pix', max_length=255, verbose_name='TxID')),
                ('qr_code', models.TextField(verbose_name='QR Code (Pix Copia e Cola)')),
                ('qr_code_image', models.URLField(blank=True, max_length=500, verbose_name='URL da Imagem QR Code')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Original')),
                ('payer_info', models.JSONField(default=dict, help_text='Nome, CPF/CNPJ, telefone, etc', verbose_name='Informações do Pagador')),
                ('payer_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Pagador')),
                ('payer_document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ do Pagador')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('reconciliation_status', models.CharField(choices=[('NOT_RECONCILED', 'Não Reconciliado'), ('RECONCILED', 'Reconciliado'), ('PARTIALLY_RECONCILED', 'Parcialmente Reconciliado'), ('ERROR', 'Erro na Reconciliação')], default='NOT_RECONCILED', max_length=30, verbose_name='Status de Reconciliação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.pixintegration', verbose_name='Integração')),
            ],
            options={
                'verbose_name': 'Transação Pix',
                'verbose_name_plural': 'Transações Pix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=255, verbose_name='ID da Fatura')),
                ('order_id', models.CharField(blank=True, max_length=255, verbose_name='ID do Pedido')),
                ('customer_id', models.CharField(blank=True, max_length=255, verbose_name='ID do Cliente')),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Reconciliado')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 a 1.0', verbose_name='Score de Confiança')),
                ('match_criteria', models.JSONField(default=dict, help_text='Campos que deram match', verbose_name='Critérios de Match')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('MATCHED', 'Match Encontrado'), ('CONFIRMED', 'Confirmado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('reconciled_at', models.DateTimeField(auto_now_add=True, verbose_name='Reconciliado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='payments.pixtransaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Reconciliação de Pagamento',
                'verbose_name_plural': 'Reconciliações de Pagamentos',
                'ordering': ['-reconciled_at'],
            },
        ),
        migrations.CreateModel(
            name='PixWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('headers', models.JSONField(default=dict, verbose_name='Headers')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='payments.pixintegration', verbose_name='Integração')),
            ],
            options={
                'verbose_name': 'Log de Webhook Pix',
                'verbose_name_plural': 'Logs de Webhooks Pix',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pixtransaction',
            index=models.Index(fields=['external_id'], name='payments_pi_externa_9d203c_idx'),
        ),
        migrations.AddIndex(
            model_name='pixtransaction',
            index=models.Index(fields=['txid'], name='payments_pi_txid_6f1204_idx'),
        ),
        migrations.AddIndex(
            model_name='pixtransaction',
            index=models.Index(fields=['status'], name='payments_pi_status_471e53_idx'),
        ),
        migrations.AddIndex(
            model_name='pixtransaction',
            index=models.Index(fields=['reconciliation_status'], name='payments_pi_reconci_2d95de_idx'),
        ),
        migrations.AddIndex(
            model_name='pixtransaction',
            index=models.Index(fields=['payer_document'], name='payments_pi_payer_d_9a759b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliation',
            index=models.Index(fields=['invoice_id'], name='payments_pa_invoice_804a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliation',
            index=models.Index(fields=['order_id'], name='payments_pa_order_i_81e519_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliation',
            index=models.Index(fields=['customer_id'], name='payments_pa_custome_28fba5_idx'),
        ),
        migrations.AddIndex(
            model_name='pixwebhooklog',
            index=models.Index(fields=['event_type'], name='payments_pi_event_t_9368ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pixwebhooklog',
            index=models.Index(fields=['processed'], name='payments_pi_process_6b8b55_idx'),
        ),
    ]
