# Generated by Django 5.1.15 on 2026-02-07 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsNotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('spike', 'Spike'), ('drop', 'Drop'), ('threshold', 'Threshold')], max_length=50)),
                ('threshold', models.FloatField(default=0)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('slack', 'Slack')], max_length=20)),
                ('channel_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnelcube.analyticsproject')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='funnelcube.analyticsproject')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_secret', models.CharField(max_length=64)),
                ('key_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('root', 'Root')], default='write', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='funnelcube.analyticsproject')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnelcube.analyticsproject')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(max_length=20)),
                ('events', models.JSONField(blank=True, default=list)),
                ('breakdowns', models.JSONField(blank=True, default=list)),
                ('formula', models.CharField(blank=True, default='', max_length=500)),
                ('interval', models.CharField(default='day', max_length=10)),
                ('range', models.CharField(default='7d', max_length=20)),
                ('previous', models.BooleanField(default=False)),
                ('metric', models.CharField(default='sum', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('layout_x', models.IntegerField(default=0)),
                ('layout_y', models.IntegerField(default=0)),
                ('layout_w', models.IntegerField(default=6)),
                ('layout_h', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='funnelcube.analyticsdashboard')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='funnelcube.analyticsproject')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('profile_id', models.CharField(blank=True, default='', max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_bounce', models.BooleanField(default=False)),
                ('entry_path', models.TextField(blank=True, default='')),
                ('exit_path', models.TextField(blank=True, default='')),
                ('screen_view_count', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('revenue', models.FloatField(default=0)),
                ('utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=255)),
                ('utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('referrer', models.TextField(blank=True, default='')),
                ('referrer_name', models.CharField(blank=True, default='', max_length=255)),
                ('referrer_type', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnelcube.analyticsproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('is_external', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('avatar', models.URLField(blank=True, default='')),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnelcube.analyticsproject')),
            ],
            options={
                'unique_together': {('external_id', 'project')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEventMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('is_conversion', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnelcube.analyticsproject')),
            ],
            options={
                'unique_together': {('project', 'event_name')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('profile_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('path', models.TextField(blank=True, default='')),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('referrer', models.TextField(blank=True, default='')),
                ('referrer_name', models.CharField(blank=True, default='', max_length=255)),
                ('referrer_type', models.CharField(blank=True, default='', max_length=50)),
                ('revenue', models.BigIntegerField(default=0)),
                ('duration', models.BigIntegerField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('os_version', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('browser_version', models.CharField(blank=True, default='', max_length=50)),
                ('device', models.CharField(blank=True, default='', max_length=50)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnelcube.analyticsproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='funnelcube__project_9acc32_idx'), models.Index(fields=['project', 'name'], name='funnelcube__project_dd558a_idx'), models.Index(fields=['project', 'profile_id'], name='funnelcube__project_b876a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSalt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnelcube.analyticsproject')),
            ],
            options={
                'unique_together': {('project', 'date')},
            },
        ),
    ]
